README.md
firestack.ios.js
ios/Firestack/Firestack.m

It's simple enough and tested (manually) to be working with my setup. Let me know if you need anything before you merge it.
Thanks!

added support for signInWithCustomToken on ios.

---

android/src/main/java/io/fullstack/firestack/FirestackDatabase.java

Fixes
```
E/unknown:React: Exception in native call
java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
at io.fullstack.firestack.FirestackDBReference.getDatabaseQueryAtPathAndModifiers(FirestackDatabase.java:235)
at io.fullstack.firestack.FirestackDBReference.addChildEventListener(FirestackDatabase.java:90)
at io.fullstack.firestack.FirestackDatabaseModule.on(FirestackDatabase.java:379)
at java.lang.reflect.Method.invoke(Native Method)
at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95) …
```

Fix startAt, endAt, equalTo optional 2nd params on Android

---

README.md

Removed leading gs:// and added a note

Changed the setStorageUrl description

---

android/src/main/java/io/fullstack/firestack/FirestackDatabase.java

Same fix as last time, just in the other method

Fix startAt, endAt, equalTo optional 2nd param for Android getDatabaseQueryAtPathAndModifiers

---

ios/Firestack/FirestackDatabase.m

As per https://github.com/fullstackreact/react-native-firestack/issues/57, this correctly sends database_error events on iOS

Correctly send database_error event on iOS

---

ios/Firestack/FirestackStorage.m

Currently the library doesn't support iOS asset-library URLs which are what the RN CameraRoll integration supplies to you.  This PR adds a check for the asset-library URL and then uses the iOS Photos library to make the image available to Firestack to then upload.
This is based off code given in one of Google's CodeLabs for Firebase: https://codelabs.developers.google.com/codelabs/firebase-ios-objc/index.html?index=..%2F..%2Findex#8

Support asset-library / camera roll URLs

---

ios/Firestack/FirestackStorage.m

So unfortunately, it seems that the security permissions for real devices are different from the simulator.  Having installed my asset change PR to an actual device this morning, it turns out that trying to upload gives a permission denied error, despite having CameraRoll permissions.
To work around this, I have changed the upload method to use putData instead of putFile and have loaded the data using the Photo library rather than relying on Firebase to resolve the filename to the data (which is where the permissions error occurred).
Sorry for not testing thoroughly enough on the first pull request, but I hadn't expected the simulator to be so different from a real device.

Change asset upload to use data rather than file

---

README.md
lib/modules/database.js

This addresses an issue where calling `.off` would remove all of the listeners for a particular query path.

Allow removal of specific callbacks from query listeners

---

android/src/main/java/io/fullstack/firestack/FirestackAuth.java

I was trying to use **react-native-google-signin** but I was receiving **error: unimplemented** until I found the problem.

Fixed provider google on Android (was missing)

---

android/src/main/java/io/fullstack/firestack/FirestackDatabase.java
android/src/main/java/io/fullstack/firestack/FirestackModule.java
android/src/main/java/io/fullstack/firestack/FirestackUtils.java

Some additional reading regarding java longs -> javascript, for those interested
http://stackoverflow.com/questions/31930406/storing-long-type-in-firebase
https://github.com/facebook/react-native/issues/9685

Android fixes - convert firebase longs to doubles, implement ServerValue.TIMESTAMP

---

android/src/main/java/io/fullstack/firestack/FirestackAuth.java

Notes:
* from what I can tell from the documentation, `user.getToken()` does not affect user data besides the token
* made `name` optional since, like `photoUrl`, firebase does not require it
* changed `provider` key used in `getUserMap()` to `providerId` as used in the other mappings
* missing equivalent implementation for iOS

Adding missing user info mapping to getUserMap (Android)

---

lib/modules/database.js

Database#off (database.js#456) calls "delete dbSubscriptions[key]" which leads to an error if the first condition is not added

fixing NPE after Database#off

---

README.md
android/src/main/java/io/fullstack/firestack/FirestackPackage.java
package.json

It's not necessary, and can be derived from the ReactApplicationContext object.
This was preventing me from compiling android on my RN 0.33 build, so I thought I'd fix it up (compiles, and am able to use Database calls properly now). Not entirely sure why I don't see any issues or pull requests about this, so I suspect I'm missing something obvious here...

Stop passing getApplicationContext() in to the constructor

---

ios/Firestack/FirestackAuth.h
ios/Firestack/FirestackAuth.m

I have found that it is possible for the first auth event to be fired before the listeningForAuth check returns true.  This results in the event not being transmitted to the front end, so is effectively lost.
This is a simple PR to set a boolean flag instead of relying on the reference to indicate whether the class is listeningForAuth;

Prevent race condition with listenForAuth (iOS)

---

lib/modules/database.js

Bug in the code that meant setPersistence is always true.

Fixed setPersistence always enabled

---

ios/Firestack/Firestack.m
ios/Firestack/FirestackDatabase.m

When the app is reloaded two exceptions occur.
1. Default app has already been configured.
2. calls to setPersistenceEnabled must be made before any other usage of FIRDatabase.
This PR fixes them.

Fix for exceptions thrown by Firebase

---

README.md
lib/modules/authentication.js

All the auth methods are on both the auth namespace and instance root. This PR moves them to the auth namespace only.

Remove auth methods from instance root & update documentation

---

android/build.gradle
android/src/main/java/io/fullstack/firestack/FirestackAuth.java
android/src/main/java/io/fullstack/firestack/FirestackDatabase.java

`user` wasn't actually being used in `userCallback`.  I changed all usages to `this.user` syntax to make it more clear if it's a field variable or not.
Similarly, the `WritableMap userMap = getUserMap();` wasn't being used, so userCallback wasn't being populated correctly

Fix auth user and user map

---

android/src/main/java/io/fullstack/firestack/FirestackAnalytics.java

getBinder is introduced in API 18, any app with a minSdk below 18 will
crash because getBinder is not there, so i changed it to getBundle which
gives the same result according to the docs.

Change getBinder to get bundle

---

android/src/main/java/io/fullstack/firestack/FirestackAuth.java

listenForAuth was not correctly checking for a user object so the user object was never populated on the callback.

Fix Android listenForAuth method to correctly check for user

---

lib/modules/database.js

* Removes trailing comma. java String#split has a different behaviour from componentsseparatedbystring, which leads to a bug.
* Problem resides in `equalTo` passing undefined to `setFilter` when no key is present.
* _Not_ tested besides `equalTo` filter in android! Can break other filters. Requires further testing.

Removing undefined's from filter arguments

---

ios/Firestack/FirestackStorage.m

- Fix weird error that NSError is not KVC compliant when storage is not configured in
JS
- Fixed code seems to exist on several more locations but has not been fixed,
since there are no tests to ensure I don't break anything.

Use storage url from .plist file if not setStorageUrl() hasn't been called

---

ios/Firestack.xcodeproj/project.pbxproj
ios/Firestack/FirestackStorage.m

fix for issue 69, missing downloadUrl property from file upload response on iOS

---

android/src/main/java/io/fullstack/firestack/FirestackAuth.java
ios/Firestack/FirestackAuth.m

getToken(true) will try to fetch token from server and fail with an exception if device is offline.

Fix android exception 

---

package.json

Add `invariant` dependency to avoid error during usage.

Add `invariant` dependency

---

android/src/main/java/io/fullstack/firestack/FirestackStorage.java
android/src/main/java/io/fullstack/firestack/FirestackUtils.java
firestack.android.js
firestack.ios.js
lib/firestack.js
lib/modules/auth.js
lib/modules/base.js
lib/modules/storage.js
lib/utils/window-or-global.js

Most of commits are self explainatory.
fd5d25d Fix broken window-or-global - fixes apps crashing when they *don't* run with the debugger open.  The error was something like "can't create new WebSocket(null)"

Various fixes

---

README.md

[Firebase.com](https://firebase.com) is the legacy console. [Firebase.google.com](https://firebase.google.com/) is the latest firebase console.

Readme link to firebase.google.com not firebase.com

---

README.md

The `.auth` was missing in the example for the Facebook Login. 
It throws an error if you copy/paste the example and run it `firestack.signInWithProvider is not a function`.

Fix example FBLogin in README.md

---

README.md

When you install `react-native-firestack` manually without using `react-native link`, you have to add 
```ruby
target '[project name]' do
end
```
to your Podfile that you created. Other wise you will get following error.
```sh
[!] The dependency `Firebase/Core` is not used in any concrete target.
The dependency `Firebase/Auth` is not used in any concrete target.
The dependency `Firebase/Storage` is not used in any concrete target.
The dependency `Firebase/Database` is not used in any concrete target.
The dependency `Firebase/RemoteConfig` is not used in any concrete target.
The dependency `Firebase/Messaging` is not used in any concrete target.
```
OS: MacOS Sierra
react-native: v0.40.0
Target: iOS 8.0

update manual install doc in README.md

---

ios/Firestack/Firestack.h
ios/Firestack/Firestack.m

This observer just calls reloadFirestack, neither of which I think is
needed (anymore?).
Hopefully resolves #218

Remove reference to RCTReloadNotification

---

ios/Firestack/Firestack.h
ios/Firestack/Firestack.m
ios/Firestack/FirestackAnalytics.h
ios/Firestack/FirestackAuth.h
ios/Firestack/FirestackCloudMessaging.h
ios/Firestack/FirestackDatabase.h
ios/Firestack/FirestackErrors.h
ios/Firestack/FirestackStorage.h

This makes Firestack work in React Native 0.40+ It will break <=0.39 though.

[v3] Fixed iOS headers to support React Native 0.40

---

lib/utils/index.js

This fixes https://github.com/fullstackreact/react-native-firestack/issues/new

[v3] Fixed bug in deepGet that returned wrong result

---

ios/Firestack/FirestackAuth.m

`getToken` should return the JWT token and not the user object. This fixes https://github.com/fullstackreact/react-native-firestack/issues/230

[v3] Fix getToken to return JWT token instead of user

---

docs/api/authentication.md

using 'facebook.com' throws an error

Fix example provider name

---

android/src/main/java/io/fullstack/firestack/database/FirestackDatabaseReference.java
ios/Firestack/FirestackDatabase.m
lib/modules/database/index.js
lib/modules/database/reference.js

Currently, it's impossible to detect errors (e.g. permission denied) when adding an .on listener to a database reference.
I've added the errorCallback option from the web spec to the .on() method and ensured this receives the correct errors.

Add error callback for database .on handler (matches Web spec)

---

Firestack.podspec
ios/Firestack/FirestackDatabase.m
package.json

I had some issues with circular references when trying to build on iOS, so have introduced a podspec to try and work around the problems.  I haven't documented yet, as I want to check that everybody is happy with it (I haven't written one before...)
Also fixed a possible null pointer exception in the iOS database module.

Add podspec and fix iOS database null pointer

---

lib/firestackModule.js

`this._firestack.database.ref(...refName)` (line 39) should be `this._firestack.database().ref(...refName)`

Make firestackModule.js working for v3

---

ios/Firestack/FirestackAuth.m
lib/modules/auth.js

The objects emitted by the `credential` method of `firebase.auth.TwitterAuthProvider`, `firebase.auth.FacebookAuthProvider`, and `firebase.auth.GoogleAuthProvider` all have different shapes. 
This lets me do
```js
var firebasejs = require('firebase');
var credential = firebasejs.auth.FacebookAuthProvider.credential(accessToken);
var auth = firestack.auth().signInWithCredential(credential);
```

Consistency with values emitted by firebase.auth.AuthProvider subclasses
